import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        {/* Run as early as possible so any extension-injected CSS custom properties
            on <html> are removed before React hydrates. This reduces hydration
            mismatch noise during development. */}
        <script
          dangerouslySetInnerHTML={{
            __html: `try{(function(){var d=document.documentElement;d.style.removeProperty('--vsc-domain');if(d.getAttribute('style')==='')d.removeAttribute('style');})();}catch(e){};`,
          }}
        />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* client content */}
        {children}
      </body>
    </html>
  );
}
